### ISSUE TITLE
Check contrast (font seems too light)

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-HousingCodeChecklist#112]

**Comment by nonprofittechy** [comment]
We can use the tool @brycestevenwilley built into ALKiln

**Comment by BryceStevenWilley** [comment]
Not a bad idea, but you'd have to add Kiln to this (which you might plan on doing anyway). With a quick check with https://wave.webaim.org/extension/ and the built in firefox contrast tools on a few individual pages, it seems that it's only the Top right username color and the blue navigation color on the left side that don't reach proper contrast.
![Screenshot from 2022-07-16 15-38-59](https://user-images.githubusercontent.com/6252212/179369692-8a3139e7-e1f6-4d1c-9c54-0a7f2bc45729.png)
![Screenshot from 2022-07-16 15-39-08](https://user-images.githubusercontent.com/6252212/179369693-cff2b485-bc3f-45f9-96c8-c605176ce4ee.png)

**Comment by miabonardi** [comment]
Neither of the previously noted issues are a part of the design anymore
