### ISSUE TITLE
Work on clear next steps documents for each action

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-HousingCodeChecklist#133]

**Comment by nonprofittechy** [comment]
These need to use the #134 letterhead when it is ready. Topics:

For the complaint:
- How to file your document in court, how to make service on LL

For an inspection request:
- How to contact an inspector
- What happens if your LL doesn't respond?

**Comment by nonprofittechy** [comment]
@gane-d @crwayne @SamAdgie these are pretty high priority, but don't need to be ready yet--we can continue to refine after getting past the MVP. But we might consider dividing them up now. Can show you some standard template formats I have used in the past.

**Comment by miabonardi** [comment]
#375
