### ISSUE TITLE
Design standard UpToCode letterhead/template/format for any documents we create that we want to have UpToCode written on

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-HousingCodeChecklist#134]
This should carry over the visual design elements from the website, including the logo, and be used for next steps documents and other education pieces.

**Comment by miabonardi** [comment]
Are the logos and the features required for this still in development? I think I could take on this issue.

**Comment by nonprofittechy** [comment]
I think you could start with the housing code report and try to carry that
look and feel over to the next steps documents.
