### ISSUE TITLE
Add a clear question "do you have a pending eviction action"?

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-HousingCodeChecklist#147]

**Comment by nonprofittechy** [comment]
If someone has a pending eviction action, they should not use UpToCode to generate a complaint.

**Comment by crwayne** [comment]
Should we create a phrase saying that they should file an Answer and Discovery if they have on? Possibly while redirecting them to MADE?

**Comment by nonprofittechy** [comment]
@crwayne we do have a specific button they can click if they are being evicted which redirects to MADE. I was thinking this will be an extra check if they start working on the complaint!
