### ISSUE TITLE
Decide if we need a longer data retention time / interview deletion window to facilitate coming back and taking next steps

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-HousingCodeChecklist#152]
See #94 

I think keeping data for 1.5 years, maybe?

But we shouldn't promise that the data will survive. More than once I have had to restore the GBLS server database from an older backup when the database dump wasn't working correctly

**Comment by tommyfurlong** [comment]
the answer to this question should go in the Privacy Plan that I have drafted in the Website channel on teams
