### ISSUE TITLE
Validation on dates when people enter the date a condition happened

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-HousingCodeChecklist#210]
If someone enters an invalid date (on the condition details screen) we should warn them

**Comment by miabonardi** [comment]
Already fixed https://github.com/nonprofittechy/docassemble-HousingCodeChecklist/blob/e3c2ea5507a58ac838a6e03daf50bbc59aabe026/docassemble/HousingCodeChecklist/data/questions/housing_code_interview.yml#L1315
