### ISSUE TITLE
“You have the right to be retaliated against” (missed the word “not”)

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-HousingCodeChecklist#234]

**Comment by miabonardi** [comment]
Fixed https://github.com/nonprofittechy/docassemble-HousingCodeChecklist/blob/e3c2ea5507a58ac838a6e03daf50bbc59aabe026/docassemble/HousingCodeChecklist/data/questions/housing_code_interview.yml#L1087
