### ISSUE TITLE
Link error: id: organizing

### ISSUE THREAD

**Issue by miabonardi** [nonprofittechy/docassemble-HousingCodeChecklist#24]
I selected the City/Life/Vida Urbana link and got the attached error. I do not know if this is just my computer. 

<img width="1017" alt="id: organizing City:Life:Vida Urbana link" src="https://user-images.githubusercontent.com/65858862/122052235-7888bf80-cdb3-11eb-87dd-871baf573356.png">

**Comment by nonprofittechy** [comment]
I get that error if I visit "https://clvu.org" but the current link says "https://www.clvu.org" and it works. I might have changed since your test.
