### ISSUE TITLE
Incorporate changes to Sanitary Code (released in January)

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-HousingCodeChecklist#255]

**Comment by miabonardi** [comment]
Most of the work is done here.

Here is the updated spreadsheet: 
[housing_code_checklist updated.xlsx](https://github.com/nonprofittechy/docassemble-HousingCodeChecklist/files/9997586/housing_code_checklist.updated.xlsx)
I included notes for the ones I could not find or if there was a change.

Here are the language changes I noticed:
“Chronic dampness” —> “excess moisture”
“Garbage” —> “refuse”
“Rodents and Insects” —> “pests”

Within the interview code itself, “Garbage” and “Rodents and Insects” are mentioned in this file:  https://github.com/nonprofittechy/docassemble-HousingCodeChecklist/blob/eafc7bbe743fa4c4092a8b0d0ad1c4e0df7ea38f/docassemble/HousingCodeChecklist/data/questions/language.yml
@nonprofittechy I will wait to change these as I am unsure of the correct translations/impact here.

**Comment by nonprofittechy** [comment]
@miabonardi no rush, but just noting while i'm looking at this:

Let's keep our language for "garbage" and "rodents and insects". I guess "Excess moisture" is better than "chronic dampness".
We made a lot of changes to the language on purpose to make it easier to read and understand.

We're going to postpone integrating this new version until March, since the new regs go into effect in April.
