### ISSUE TITLE
Tweak feedback widget - maybe "Did we help you?"

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-HousingCodeChecklist#291]

**Comment by miabonardi** [comment]
Is this still open?

**Comment by miabonardi** [comment]
![Screen Shot 2023-03-24 at 9 38 44 AM](https://user-images.githubusercontent.com/65858862/227536300-473920f5-47c3-4d11-b081-236dea15fd88.png)
