### ISSUE TITLE
Add an explanation that complaint will have a demand for 93A and you can ask to update the complaint 

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-HousingCodeChecklist#316]
![image](https://user-images.githubusercontent.com/7645641/221224461-76aaad2a-ddd1-40a2-ae99-a6272ccefa8b.png)

**Comment by miabonardi** [comment]
Add a note that pops up on selection to remind user they will get both the demand letter and 93A and that they can update the complaint 

Later addition is a reminder feature
