### ISSUE TITLE
Review screen for complaint is not finished

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-HousingCodeChecklist#322]
We are referencing `review_verified_complaint_and_motions` but this is an unfinished review screen.

Maybe create a new one with the review screen generator that is in the Dashboard? It could be a standalone YAML file if that seems simplest.

**Comment by miabonardi** [comment]
Dashboard did not work with `verified_complaint_and_motions_to_include.yml`. @nonprofittechy let me know when dashboard is compatible or if I should proceed manually.

**Comment by nonprofittechy** [comment]
Review screen generator should work wit this file now
