### ISSUE TITLE
Add information?

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-HousingCodeChecklist#327]
Question mark help issues
Add Lead test resource: https://eohhs.ehs.state.ma.us/leadsafehomes/default.aspx.

**Comment by nonprofittechy** [comment]
In order to answer `landlord_rents_other_property` user should be provided with other information i.e. https://www.masslandrecords.com/

**Comment by miabonardi** [comment]
> Lead

How should I add this one if it is the help text loaded in from the spreadsheet?
