### ISSUE TITLE
Cleanup some language on `verified_complaint_claims[i]`

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-HousingCodeChecklist#336]
Verified_complaint_claims[i]
“More information about when your LL….” 
“Complete the sentence” vs “1-2 sentences” was confusing 
“Last summer” vs “include a year” was confusing
Recommended “summer 2021” instead
User thought they were asked same question twice
Consider making “More information about when your LL….” not bold to differentiate between claim screens

**Comment by miabonardi** [comment]
Was not clear that the label of or answer to `verified_complaint_claims[i].details` would be included in the final document. Consider adding text to explain which text will appear on final doc.
