### ISSUE TITLE
Rename "download zip" to something more general knowledge

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-HousingCodeChecklist#337]
An advocate wasn't familiar with the word Zip. Also observed people weren't aware this button let them download all documents at once.

We still need something relatively short, and possibly this should get fixed upstream?

**Comment by miabonardi** [comment]
Maybe just "all" as most people will understand this in context to mean all their documents?

**Comment by miabonardi** [comment]
Updates in AL
