### ISSUE TITLE
Attachments bug(s)?

### ISSUE THREAD

**Issue by miabonardi** [nonprofittechy/docassemble-HousingCodeChecklist#357]
Found during user testing Mar 29. Recording available. 

Error
pandas.core.frame.DataFrame object has no element ‘URL’ Filename: next_steps_inspection_request_letter.docx

**Comment by miabonardi** [comment]
Full Error: [MADE_ UpToCode.pdf](https://github.com/nonprofittechy/docassemble-HousingCodeChecklist/files/11104911/MADE_.UpToCode.pdf)

**Comment by miabonardi** [comment]
turn on `skip undefined: True` in attachment block

**Comment by miabonardi** [comment]
Is this the same error as above @nonprofittechy? User testing on 3/30 could download docs on review but could not sign and download because hit this error.

![Screen Shot 2023-03-30 at 5 34 24 PM](https://user-images.githubusercontent.com/65858862/228970065-63634d1d-5384-446d-979d-4de9980cd074.png)

**Comment by miabonardi** [comment]
Demand letter did not show on download when only one in the flow. Only Housing Conditions Report did

**Comment by miabonardi** [comment]
> Demand letter did not show on download when only one in the flow. Only Housing Conditions Report did

Happened again on 4/11

**Comment by miabonardi** [comment]
> > Demand letter did not show on download when only one in the flow. Only Housing Conditions Report did
> 
> Happened again on 4/11

seems demand letter is not enabled

**Comment by miabonardi** [comment]
> > Is this the same error as above @nonprofittechy? User testing on 3/30 could download docs on review but could not sign and download because hit this error.
> > ![Screen Shot 2023-03-30 at 5 34 24 PM](https://user-images.githubusercontent.com/65858862/228970065-63634d1d-5384-446d-979d-4de9980cd074.png)
> 
> Replicated this error again 4/12

Unclear to me why `affidavitofindigency_attachment._is_docx` is not returning `False` since it is a PDF: https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/6d337b5869352a26b2ae27bde7bfef0a241d2a89/docassemble/AssemblyLine/al_document.py#L775-L782

@nonprofittechy This is currently preventing the fee waiver download in UpToCode.

**Comment by miabonardi** [comment]
@nonprofittechy 

To replicate: 

go down any path to file something in court and then say you want to see if you qualify for fee waiver

**Comment by nonprofittechy** [comment]
Should be closed by https://github.com/SuffolkLITLab/docassemble-AssemblyLine/pull/684

**Comment by miabonardi** [comment]
> > > Is this the same error as above @nonprofittechy? User testing on 3/30 could download docs on review but could not sign and download because hit this error.
> > > ![Screen Shot 2023-03-30 at 5 34 24 PM](https://user-images.githubusercontent.com/65858862/228970065-63634d1d-5384-446d-979d-4de9980cd074.png)
> > 
> > 
> > Replicated this error again 4/12
> 
> Unclear to me why `affidavitofindigency_attachment._is_docx` is not returning `False` since it is a PDF: https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/6d337b5869352a26b2ae27bde7bfef0a241d2a89/docassemble/AssemblyLine/al_document.py#L775-L782
> 
> @nonprofittechy This is currently preventing the fee waiver download in UpToCode.

Resolved.

**Comment by miabonardi** [comment]
> > > Demand letter did not show on download when only one in the flow. Only Housing Conditions Report did
> > 
> > 
> > Happened again on 4/11
> 
> seems demand letter is not enabled

Resolved.

**Comment by miabonardi** [comment]
@nonprofittechy any reason you reopened this issue? I just retested the two I saw and they are good now.

**Comment by nonprofittechy** [comment]
Hasn't been merged with Assembly Line yet
