### ISSUE TITLE
Make sure verified complaint title handles if there are no conditions selected

### ISSUE THREAD

**Issue by miabonardi** [nonprofittechy/docassemble-HousingCodeChecklist#376]
Verified complaint will generate if user just says it is a quiet enjoyment issue and that there are no repairs needed. The complaint in this context does not make sense because it is tailored for repair context.

**Comment by miabonardi** [comment]
Complaint language should update if repairs is not mentioned 

include_conditions_in_complaint 

update title

**Comment by miabonardi** [comment]
Don't generate Housing Conditions Report for this path

**Comment by miabonardi** [comment]
> include_conditions_in_complaint = initial_action_selection in ["document_by_room", "give_notice"] or (initial_action_selection == "help_in_court" and kind_of_lawsuit.any_true("get_emergency_repairs", "past_repair_needs"))
> 
> initial_action_selection in ["document_by_room", "give_notice"] should not be here. "document_by_room" is the card on the initial page where user chooses to "explore problems" but the user can still go through this path and select 0 repair issues. "give_notice" is a commented out selection and appears to be holdover

Resolved.

**Comment by miabonardi** [comment]
@nonprofittechy how do I make the actual title of the document conditional? This code block does not effect it: 

https://github.com/nonprofittechy/docassemble-HousingCodeChecklist/blob/741009fa2a9adbdd4b9dff5c8863ba34784dc54f/docassemble/HousingCodeChecklist/data/questions/verified_complaint_and_motions_to_include.yml#L761-L771


![Screen Shot 2023-04-24 at 6 33 28 PM](https://user-images.githubusercontent.com/65858862/234131849-20c31b19-4d3b-4f05-a6aa-1d68ff41afa0.png)

**Comment by nonprofittechy** [comment]
It's a property of the Word file itself. You can tell Docassemble to edit that, but it sometimes results in glitches to numbering, etc. because it uses LibreOffice to do it
