### ISSUE TITLE
Add new community group

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-HousingCodeChecklist#75]
Community Action Agency of Somerville (CAAS)
66-70 Union Square, Suite 204, Somerville, MA 02143
617-539-6282
https://www.caasomerville.org/community-organizing

**Comment by miabonardi** [comment]
Already added https://github.com/nonprofittechy/docassemble-HousingCodeChecklist/blob/e3c2ea5507a58ac838a6e03daf50bbc59aabe026/docassemble/HousingCodeChecklist/data/questions/customized_screens.yml#L422-L427
